---
name: Changelog
concurrency: opa-changelog
on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release-please:
        name: Prepare Release notes
        runs-on: ubuntu-latest
        steps:
            - id: release-please
              uses: GoogleCloudPlatform/release-please-action@v3
              with:
                  release-type: go
                  package-name: opa-plugin
                  token: ${{ secrets.INDYKITEONE_PAT }}
