---
name: Lint
on:
    pull_request:
        types: [opened, synchronize, reopened]

    # Run on master too to save cache, which can be shared into PR too
    push:
        branches:
            - master

jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: ^1.19

            - name: Checkout codebase
              uses: actions/checkout@v3

            - name: Run GolangCI-Lint Scanner
              uses: golangci/golangci-lint-action@v3
              with:
                  # Required: the version of golangci-lint is required and must be specified without patch version.
                  version: v1.51

                  # Optional: golangci-lint command line arguments.
                  args: --timeout 2m00s
