---
name: Test
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - master
        tags:
            - '!*' # Do not execute on tags

    # Run on master too to report coverage on master branch to Codecov
    push:
        branches:
            - master

concurrency:
    group: pr-${{ github.ref }}
    cancel-in-progress: true


jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: go.mod

            - name: Run Unit tests.
              run: |
                  make test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.out
                  # Notify us when failed, so devs are not waiting for Codecov report when it will never come.
                  # Because Codecov report is required to be able to merge, we have to run again the whole test anyway.
                  fail_ci_if_error: true

    trivy-config-scan:
        name: trivy config scan
        runs-on: ubuntu-latest
        steps:
            - name: Check out jarvis-proto code
              uses: actions/checkout@v4
            - name: Create .trivyignore file
              run: echo '${{ vars.TRIVY_IGNORE }}' > .trivyignore
            - uses: aquasecurity/trivy-action@0.11.2
              with:
                  scan-type: config
                  # Scan only directory, where Dockerfiles are, until Trivy issue is fixed
                  # https://github.com/aquasecurity/trivy/issues/3212
                  scan-ref: .
                  exit-code: '1'
                  severity: HIGH,CRITICAL
                  trivyignores: .trivyignore
